GET /users
Host: localhost:8080

###

POST /users
Host: localhost:8080
Content-Type: application/json

{"name":"hola","email":"marioyluigi87@gmail.com","password":"password"}

###

GET /tasks
Host: localhost:8080

###

POST /tasks
Host: localhost:8080
Content-Type: application/json

{
        "userId": "1",
        "columnId": 1,
        "text": "asasas",
        "isCompleted": false
               
}

###
DELETE /tasks/1
Host: localhost:8080

###
PUT /tasks/1
Host: localhost:8080
Content-Type: application/json

{
    
        "userId": "1",
        "columnId": 1,
        "text": "asasas",
        "isCompleted": true,       
        "createdAt": "7/31/2023, 12:17:40 AM"       
    
}


