POST /api/v1/users
Host: localhost:8080
Content-Type: application/json

{"name":"israel","email":"israel@gmail.com","password":"israel"}

###

POST /api/v1/session
Host: localhost:8080
Content-Type: application/json

{"email":"israel@gmail.com","password":"israel"}

###

PUT /api/v1/users/64d7b7d9aa6b97e2e8c29f5c
Host: localhost:4040
Content-Type:  application/json

{"email":"israelnew@gmail.com","password":"israel"}

###

GET /api/v1/tasks
Host: localhost:8080

###

POST /api/v1/tasks
Host: localhost:8080
Content-Type: application/json

{
        "userId": "1",
        "columnId": 1,
        "text": "asasas",
        "isCompleted": false
               
}

###
DELETE /api/v1/tasks/64d59e02fb4a34bec78911f2
Host: localhost:8080

###
PUT /api/v1/tasks/64d8281b1d6c009d1cc1fda8 
Host: localhost:4040
Content-Type: application/json

{
    
        "userId": "1",
        "columnId": 1,
        "text": "asasas",
        "isCompleted": true       
        
    
}

###

GET /api/v1/column
Host: localhost:8080

###

POST /api/v1/column
Host: localhost:8080
Content-Type: application/json

{
        "userId":"1",
        "columnId":"1",
        "text":"titulo de la columna 1",
        "boardId":"id del board"
    
}


