### obtener tareas de un usuario en específico

GET /api/v1/tasks
Host: localhost:4040
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ5OTgxOWRkN2ZiNjcxNTNjNDYxNWUiLCJpYXQiOjE2OTE5ODE4NzR9.4fcQ_yrnS3U8jcjdleG2kV909G8BnaT9mEnBrMNPR5I

### guardar una tarea

POST /api/v1/tasks
Host: localhost:4040
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRjZWI4NzBlZjVmZGFjMzExZjQwNWYiLCJpYXQiOjE2OTIxOTk5NjIsImV4cCI6MTY5MjIwMzU2Mn0.C3nS9wTsC2vgBBkwB12eKMY2Ldybwd2470BzwRl3SYc

{      
        "columnIndex": 1,
        "text": "tarea de prueba 3",
        "isCompleted": false,
        "columnId":"64da7b6f2821234f1ff20782"             
}

### eliminar tarea

DELETE /api/v1/tasks/64d99870dd7fb67153c46166 
Host: localhost:4040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ5OTgxOWRkN2ZiNjcxNTNjNDYxNWUiLCJpYXQiOjE2OTE5ODE4NzR9.4fcQ_yrnS3U8jcjdleG2kV909G8BnaT9mEnBrMNPR5I

### actualizar tarea

PUT /api/v1/tasks/64dc485f696574bfb4a6b9d0 
Host: localhost:4040
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRiYTllY2Y2ZGUwZGExN2M4NjE3MmIiLCJpYXQiOjE2OTIxNjE5MDQsImV4cCI6MTY5MjE2NTUwNH0.A04fWrswBLhOxtTqEk3-tZXUMN-zo5Aas1HL5BgUUEo

{   
        
        "columnIndex": 3,
        "text": "modificado",
        "isCompleted": false
        
    
}