### registrar usuario

POST /api/v1/users
Host: localhost:4040
Content-Type: application/json

{"name":"user","email":"user@gmail.com","password":"user"}

### actualizar usuario

PUT /api/v1/users
Host: localhost:4040
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRhNjQyNWVjMTkwYTNiOTcyODg0MmEiLCJpYXQiOjE2OTIxMTYyMjAsImV4cCI6MTY5MjExNjI1MH0.QBSbeTMvQ6fIAdUEPfBDIlg5ymqclGgqguriTlZJMD0

{"email":"danielother@gmail.com"}

### Eliminar usuario 

DELETE /api/v1/users
Host: localhost:4040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRhNWJhNjNiN2U4NzFjNTI4MjJhNzMiLCJpYXQiOjE2OTIwNDMzMTZ9.ST319895ES2xB-klq7mfToeHiiawYsul01UhG2DQofs




