### registrar usuario

POST /api/v1/users
Host: localhost:4040
Content-Type: application/json

{"name":"daniel","email":"daniel@gmail.com","password":"daniel"}

### actualizar usuario

PUT /api/v1/users
Host: localhost:4040
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRjNWY4ZTkyZjZkMGNhNmE1MTg2MTIiLCJpYXQiOjE2OTIxNzkyMzYsImV4cCI6MTY5MjE4MjgzNn0.llkutFFc_yulW_vp2iG5Y9x9SLU63C6npUFL0unA2Ik

{
    "email":"danielother@gmail.com",
    "name":"israelnew",
    "password":"asasaasasasqwewewdsd"    
    
}

### Eliminar usuario 

DELETE /api/v1/users
Host: localhost:4040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRjZWI4NzBlZjVmZGFjMzExZjQwNWYiLCJpYXQiOjE2OTIxOTk5NjIsImV4cCI6MTY5MjIwMzU2Mn0.C3nS9wTsC2vgBBkwB12eKMY2Ldybwd2470BzwRl3SYc




